### ISSUE TITLE
[Notes] AttributeError: 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by Kuro-Rui** [i-am-zaidali/cray-cogs#28]
Traceback:
```py
Exception during loading of package
Traceback (most recent call last):
  File "C:\Users\User\T.D.L\lib\site-packages\redbot\core\core_commands.py", line 172, in _load
    await bot.load_extension(spec)
  File "C:\Users\User\T.D.L\lib\site-packages\redbot\core\bot.py", line 1561, in load_extension
    await lib.setup(self)
  File "C:\Users\User\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\tdl\cogs\CogManager\cogs\notes\__init__.py", line 11, in setup
    cog = await Notes.initialize(bot)
  File "C:\Users\User\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\tdl\cogs\CogManager\cogs\notes\notes.py", line 80, in initialize
    await self.to_cache()
  File "C:\Users\User\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\tdl\cogs\CogManager\cogs\notes\notes.py", line 52, in to_cache
    guild.id: {
AttributeError: 'NoneType' object has no attribute 'id'
```
Anyways, sorry for another Issue today 😓

**Comment by i-am-zaidali** [comment]
Should be fixed by 17d4a73be7f0a78d40b138865911b141df5f9b45
