### ISSUE TITLE
[Giveaways] NoneType object has no attribute 'id'

### ISSUE THREAD

**Issue by ltzmax** [i-am-zaidali/cray-cogs#31]
This seems to post to logs every once in a while.
Full traceback below:
```py
Traceback (most recent call last):
   File "/home/max/redenv/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
     await coro(*args, **kwargs)
     File "/home/max/redbot/cogs/CogManager/cogs/giveaways/main.py", line 382, in on_command_completion
     settings = await get_guild_settings(ctx.guild.id)
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by i-am-zaidali** [comment]
Fixed
