### ISSUE TITLE
[Notes] [Error]

### ISSUE THREAD

**Issue by cag1585** [i-am-zaidali/cray-cogs#37]
I'm getting this error on `notes <user>`
```py
Traceback (most recent call last):
  File "/home/db/redenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/db/redbot/cogs/CogManager/cogs/notes/notes.py", line 285, in notes
    embs := await self.group_embeds_by_fields(
  File "/home/db/redbot/cogs/CogManager/cogs/notes/notes.py", line 126, in group_embeds_by_fields
    discord.Embed.from_dict(**kwargs)
TypeError: from_dict() got an unexpected keyword argument 'author'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/db/redenv/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/db/redenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/db/redenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: from_dict() got an unexpected keyword argument 'author'
```

**Comment by i-am-zaidali** [comment]
Hey! Real sorry I completely forgot this issue existed. But that error was fixed a long time ago with 0136efb054c4e90487ad63143933670f59d10037 :)
